### PR TITLE
Init Project

### PR DESCRIPTION
**Pull request by anhdh-3069**
ready

### CODE REVIEW

**Comment by anhdh-3069** [comment]
ready

**Comment by ngocvt-0484** [comment]
tham khảo comment pull này fix xong rồi đẩy lên e nhé https://github.com/hieupt-121262/sample_app/pull/1

**Comment by ngocvt-0484** [comment]
commented

**Comment by anhdh-3069** [comment]
ready

**Review by anlvq-1058 — COMMENTED** [review]
2 commit em ơi

**Comment by anhdh-3069** [comment]
ready

**Comment by ngocvt-0484** [comment]
merged

**Pull request merged**
